#!/bin/bash -eu

if [ ! "$DOCKER_MACHINE_NAME" ] && [ ! "$1" ]; then
	echo "Usage: docker-machine doctor <name>"
	exit 1
fi

NAME="${DOCKER_MACHINE_NAME:-1}"
SSH="docker-machine ssh $NAME"
FS="/mnt/sda1"
SIZE=10


STATUS="$(docker-machine status $NAME)"
if [ "$STATUS" != "Running" ]; then
	echo "Docker Machine $NAME not running: $STATUS"
	exit 1
fi

DRIVER="$(docker-machine inspect --format="{{.DriverName}}" $NAME)"
if [ "$DRIVER" != "virtualbox" ]; then
	echo "Docker Machine $NAME driver not supported: $DRIVER"
	exit 1
fi

MOUNT="$($SSH test -e /dev/sda1 2> /dev/null ; echo $?)"
if [ "$MOUNT" != "0" ]; then
	echo "Docker Machine $NAME has no hard disk mounted"
	exit 1
fi

_header () {
	echo
	echo
	echo -e "\033[1;37m$@\033[0m"
}

_header "Docker client and server version:"
docker version

_header "Docker machine version:"
docker-machine -version

_header "Intermediate images:"
$SSH 'docker images' | awk '$1 == "<none>" {print $3}'

_header "Containers:"
$SSH 'docker ps --all --format="table {{.ID}}\t{{.Image}}\t{{.Size}}"'

_header "Filesystem mounts:"
$SSH 'sudo df -a -T -h -m' | sort -k 6 -r

_header "Disk space usage: Containers:"
$SSH "sudo du -sh $FS/var/lib/docker/containers/"
echo
$SSH "sudo find $FS/var/lib/docker/containers/ -type f -print0 | xargs -0 sudo du -a -m 2> /dev/null" \
	| sort -n -r \
	| ( grep -m $SIZE -v "^0" || : ) \
	| sed "s/\([0-9]\+\)/\1M/"

_header "Disk space usage: Volumes:"
$SSH "sudo du -sh $FS/var/lib/docker/volumes/"
echo
$SSH "sudo find $FS/var/lib/docker/volumes/ -type f -print0 | xargs -0 sudo du -a -m 2> /dev/null" \
	| sort -n -r \
	| ( grep -m $SIZE -v "^0" || : ) \
	| sed "s/\([0-9]\+\)/\1M/"

_header "Disk space usage: Filesystem:"
$SSH "sudo du -sh $FS/var/lib/docker/aufs/diff/"
echo
$SSH "sudo find $FS/var/lib/docker/aufs/diff/ -type f -print0 | xargs -0 sudo du -a -m 2> /dev/null" \
	| sort -n -r \
	| ( grep -m $SIZE -v "^0" || : ) \
	| sed "s/\([0-9]\+\)/\1M/"

_header "Disk space usage: Temporary files:"
$SSH "sudo du -sh $FS/var/lib/docker/tmp/ $FS/tmp/ $FS/lost+found/"
echo
$SSH "sudo find $FS/var/lib/docker/tmp/ -type f -print0 | xargs -0 sudo du -a -m 2> /dev/null" \
	| sort -n -r \
	| ( grep -m $SIZE -v "^0" || : ) \
	| sed "s/\([0-9]\+\)/\1M/"
$SSH "sudo find $FS/tmp/ -type f -print0 | xargs -0 sudo du -a -m 2> /dev/null" \
	| sort -n -r \
	| ( grep -m $SIZE -v "^0" || : ) \
	| sed "s/\([0-9]\+\)/\1M/"
$SSH "sudo find $FS/lost+found -type f -print0 | xargs -0 sudo du -a -m 2> /dev/null" \
	| sort -n -r \
	| ( grep -m $SIZE -v "^0" || : ) \
	| sed "s/\([0-9]\+\)/\1M/"
